# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.0.9
_src_path: https://github.com/jupyterlab/extension-template
author_email: aaronrmm@gmail.com
author_name: Aaron Margolese-Malin
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab-voicechain
mimetype: ''
mimetype_name: ''
project_short_description: A Jupyterlab extension that provides voice commands for
    AI code completion with LangChain.
python_name: jupyterlab-voicechain
repository: https://github.com/aaronrmm/jupyterlab-voicechain
test: true
viewer_name: ''

